### ISSUE TITLE
Change setup.py to provide cloudtsa package instead of iter8 package

### ISSUE THREAD

**Issue by sriumcp** [istio-ecosystem/iter8#1]
The main purpose of the `setup.py` file at present is to get the `cloudtsa` unit tests to pass. It does this by providing the `iter8` python package -- relative to which all the `cloudtsa` import statements are resolved.   Given this: 

I propose that we modify the `setup.py` file to directly provide the `cloudtsa` package as opposed to the (broader) `iter8` package (which also includes `istio-analytics` apart from `cloudtsa`). 

This will make the package definition more modular, by restricting it to `cloudtsa`.

**Comment by fabolive** [comment]
@sriumcp: I would further suggest that setup.py moves into the `cloudtsa` subdirectory, and that we remove the `iter8` subdirectory, i.e., `cloudtsa` and `istioanalytics` move one level up.
